### ISSUE TITLE
Extending @playwright/test 1.12

### ISSUE THREAD

**Issue by denovodavid** [hoverinc/playwright-testing-library#251]
`@playwright/test` `1.12` is self-contained and basically re-exports `playwright`.
This breaks extending as all the objects and types are now from the `@playwright/test` package and not the `playwright` package.

**Comment by jrolfs** [comment]
Hi @denovodavid, thanks for reporting this. I just recently became aware of **@playwright/test**. We've had some recent issues with **jest-playwright** (see #140) that touches on some of these same issues. I'm really trying to find the time to get back in here and move CI into GitHub actions and add support for **@playwright/test** soon. Please feel free to open up a PR in the meantime, otherwise I will keep you posted.

**Comment by jrolfs** [comment]
Ah, one more thing: if you do plan on working on a PR let me know and I'll make sure to at least get CI sorted for you.

**Comment by Zache** [comment]
Is it just extend that breaks with @playwright/test or also the standalone queries?

**Comment by jrolfs** [comment]
I think the main issue here is the way that Playwright distributes the different "flavors" of the library as I described here: https://github.com/hoverinc/playwright-testing-library/pull/295#issuecomment-924421199

**Comment by jrolfs** [comment]
Alright, so a working version of this is available at https://www.npmjs.com/package/@playwright-testing-library/test/v/4.0.0-beta.10 for anyone that wants to try it. You can see the updated readme [on the **beta** branch](https://github.com/hoverinc/playwright-testing-library/tree/beta).

**Comment by Zache** [comment]
> Actually, [maybe this could be implemented as a selector engine](https://github.com/microsoft/playwright/blob/da1dafcadb05fd648f13610d8eefc4baa5c2261e/docs/src/extensibility.md)?

There's no maybe about it: https://github.com/hoverinc/playwright-testing-library/pull/330

**Comment by jrolfs** [comment]
**@playwright/test** is now officially supported in 4.0.1 under the name [**@playwright-testing-library/test**](https://www.npmjs.com/package/@playwright-testing-library/test/v/4.0.1) via #315.

Note: unfortunately I messed up and published a **4.0.0** on the _next_ distribution channel while I was sorting the CI process, hence **4.0._1_** ... 🤦🏼‍♂️ .

I'm going to close this and let's continue the selector engine discussion in #330 or a new issue.
